add dispatch command + move functions to helpers in order to reuse them
OpsInc/enroller-client pull request #2
Opened 2024-02-02 05:40 UTC by ssim-krassimir

2024-02-02 06:03 UTC, jad617 requested changes
jai laisser 3 inline comments

2024-02-02 06:03 UTC, jad617 commented on cmd/dispatch.go
> +	authOptions = "List of supported authentication methods values: [cognito]"
a changer

2024-02-02 06:03 UTC, jad617 commented on cmd/dispatch.go
> +	dispatchCmd.PersistentFlags().StringVarP(&auth, "auth", "a", "cognito", authOptions)
ca aussi faut enlever cognito

2024-02-02 06:03 UTC, jad617 commented on cmd/helpers.go
> +	PrNumber string `json:"prNumber"`
PrNumber string `json:"prNumber,omitempty"`

2024-02-02 06:05 UTC, jad617 commented on cmd/dispatch.go
> +	dispatchCmd.PersistentFlags().StringVarP(&auth, "auth", "a", "cognito", authOptions)
il faut rajouter --branch qui overide la variable d'environment BRANCH
ou bien ne pas rajouter --branch et simplement laisser le pipeline mettre la bonne branch dans le post-merge.yaml pipeline a voir ce qui est mieux

2024-02-06 22:17 UTC, ssim-krassimir commented on cmd/helpers.go
> +	PrNumber string `json:"prNumber"`
done

2024-02-06 22:18 UTC, jad617 approved these changes

2024-02-06 22:24 UTC, merged